### ISSUE TITLE
Feature Request: Mutes, Timeouts, and Slowmode

### ISSUE THREAD

**Issue by grepsedawk** [the-business-factory/hirobot.app#2]
A featureset of discord that is missing on slack, which appeal more to communities than teams:

Mute means they can lurk but not talk
Timeouts is "mute for x minutes" to allow for mod to handle heated discussions
slowmode is "1 post per x timeframe" for stuff like work offers

**Comment by robcole** [comment]
Closing this as mute isn't an option on Slack, but #3 talks about some potential workarounds, depending on need.

**Comment by grepsedawk** [comment]
> mute isn't an option on Slack

Yeah, that would be the full feature add. It'd need to lurk for messages from specific users and delete them right away. Good for "Whoa what's going on here" mod intervention
