### ISSUE TITLE
Feature research: bot deleting posts as admin

### ISSUE THREAD

**Issue by robcole** [the-business-factory/hirobot.app#3]
Related to #2, there's no mute functionality on Slack on a global level, just muting notifications. 

What theoretically could work is adding "Login with Slack" -- then having an admin login and pass the authorization token to the bot. This would allow for a "during X timeframe, delete all posts that are made in this thread, and post an ephemeral user to that message that conversation is paused or they are rate limited." 

Here's what Slack's API says about message deletion:

> This method deletes a message from a conversation.

> When used with a user token, this method may only [delete messages that user themselves can delete in Slack](https://slack.com/intl/en-ie/help/articles/202395258-Edit-or-delete-messages).

> When used with a bot token, this method may delete only messages posted by that bot.

Since admins can delete any messages, this might work, but is a bit of a hack. @grepsedawk any thoughts?

**Comment by grepsedawk** [comment]
@robcole when you login via oauth you should get 2 tokens, a "bot" token and a "user API token" and if that "user API token" is an admin, you should be able to use that to delete messages I believe!
I did this in the ruby lib awhile back it was something like that

**Comment by robcole** [comment]
This has been implemented, Slack gives admin permissions to be able to delete posts when the app is installed by an admin.
